from pathlib import Path
import hashlib
import json
import shutil
from datetime import datetime, timezone


ROOT = Path(__file__).resolve().parents[2]

PROCESSED = ROOT / "data" / "processed"
SUBMISSION = ROOT / "submission"

# Final outputs that are actually generated by your pipeline
REQUIRED_FILES = [
    "graphone_final_dataset.json",
    "graphone_data_quality_report.json",
    "graphone_submission_dataset.xlsx",
    "ai_entities_classified.json",
    "entity_resolution.json",
    "entity_index.json",
    "research_papers_extracted.json",
    "research_papers_linked.json",
    "startups_products_raw.json",
    "fresh_ai_data.json",
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()

    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)

    return h.hexdigest()


def main():
    print("=" * 70)
    print("GRAPHONE FINAL SUBMISSION PREPARER")
    print("=" * 70)

    SUBMISSION.mkdir(
        parents=True,
        exist_ok=True
    )

    manifest = {
        "project": "GraphOne AI Ecosystem Data Pipeline",
        "generatedAt": datetime.now(
            timezone.utc
        ).isoformat(),
        "files": [],
    }

    missing = []

    for filename in REQUIRED_FILES:

        source = PROCESSED / filename

        if not source.exists():
            missing.append(filename)
            continue

        destination = SUBMISSION / filename

        shutil.copy2(
            source,
            destination
        )

        manifest["files"].append({
            "name": filename,
            "sizeBytes": destination.stat().st_size,
            "sha256": sha256(destination),
        })

        print(f"Copied: {filename}")

    # Save manifest
    manifest_path = SUBMISSION / "submission_manifest.json"

    with manifest_path.open(
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            manifest,
            f,
            indent=2,
            ensure_ascii=False
        )

    print()
    print("=" * 70)
    print("SUBMISSION PREPARATION COMPLETE")
    print("=" * 70)

    print(
        f"Files copied : {len(manifest['files'])}"
    )

    print(
        f"Files missing: {len(missing)}"
    )

    if missing:
        print()
        print("MISSING FILES:")
        for filename in missing:
            print(f"  - {filename}")

    print()
    print(f"Submission folder: {SUBMISSION}")

    if not missing:
        print()
        print("STATUS: READY FOR DOCUMENTATION")
    else:
        print()
        print("STATUS: CHECK MISSING FILES")


if __name__ == "__main__":
    main()